### ISSUE TITLE
test

### ISSUE THREAD

**Issue by b232wang** [b232wang/casino#1]
0x8fef2229291b68be841adf029e58b87f39ba144b2d3b0af1760243d0a9bc6a1c

**Comment by b232wang** [comment]
0x12088237BE120f6516287a74fC01B60935B1cf89

**Comment by b232wang** [comment]
Running migration: 2_migrate_presale.js
  Deploying Token...
  ... 0x50d2f45ce4b6795e43bc1bfee2f099efc6b68b3c47000e885d15fdc4f1bef3f4
  Token: 0x1d306dab8b12ea53dbaa851020b75a0b13f4c8d5
Saving successful migration to network...
===Token address:  0x1d306dab8b12ea53dbaa851020b75a0b13f4c8d5
Token address:  0x1d306dab8b12ea53dbaa851020b75a0b13f4c8d5
(node:1647) UnhandledPromiseRejectionWarning: Error: Presale has no network configuration for its current network id (1337).
    at Function.network (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:721:1)
    at Function.getter (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:660:1)
    at Function.get (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:742:1)
    at Function.getter (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:657:1)
    at module.exports (/root/projects/Sale/migrations/2_migrate_presale.js:16:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1647) UnhandledPromiseRejectionWarning: Error: Cannot link library: SafeMath has no address. Has it been deployed?
    at Object.link (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-deployer/src/linker.js:25:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-deployer/src/actions/link.js:5:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
  Deploying SafeMath...
  Deploying Presale...
  ... 0x01411edbc481e0318b2fcee9fcdcb7ce2f00e505e0b51ce713c45fc1b1b044e6
  ... 0xfc198b7f180fd7af49d7cbfe4c58ee25a8feb3b9aa44ee98a9d5559561980baa
  ... 0x0f040de51d035d2ecee19a6fa15a3005b73f467db4b11beae082f276e206eb80
Saving artifacts...
  SafeMath: 0x424c29e9a6ebc336a9f0c3998edf81b7e64ad7fc
(node:1647) UnhandledPromiseRejectionWarning: Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-migrate/index.js:225:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:1647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
